# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/article.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protos/article.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/article.proto\"J\n\x07\x41rticle\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x04 \x01(\t\"5\n\x12\x41rticleListRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"1\n\x13\x41rticleListResponse\x12\x1a\n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x08.Article\"\"\n\x14\x41rticleDetailRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x15\x41rticleDetailResponse\x12\x19\n\x07\x61rticle\x18\x01 \x01(\x0b\x32\x08.Article2\x88\x01\n\x0e\x41rticleService\x12\x38\n\x0b\x41rticleList\x12\x13.ArticleListRequest\x1a\x14.ArticleListResponse\x12<\n\rArticleDetail\x12\x15.ArticleDetailRequest\x1a\x14.ArticleListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.article_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTICLE']._serialized_start=24
  _globals['_ARTICLE']._serialized_end=98
  _globals['_ARTICLELISTREQUEST']._serialized_start=100
  _globals['_ARTICLELISTREQUEST']._serialized_end=153
  _globals['_ARTICLELISTRESPONSE']._serialized_start=155
  _globals['_ARTICLELISTRESPONSE']._serialized_end=204
  _globals['_ARTICLEDETAILREQUEST']._serialized_start=206
  _globals['_ARTICLEDETAILREQUEST']._serialized_end=240
  _globals['_ARTICLEDETAILRESPONSE']._serialized_start=242
  _globals['_ARTICLEDETAILRESPONSE']._serialized_end=292
  _globals['_ARTICLESERVICE']._serialized_start=295
  _globals['_ARTICLESERVICE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
